version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ultimate-crud-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ultimate_crud_blog
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: blogpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data/database-mysql.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    networks:
      - ultimate-crud-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: ultimate-crud-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ultimate_crud_blog
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/database-postgresql.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    networks:
      - ultimate-crud-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bloguser -d ultimate_crud_blog"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer - Database Management Tool
  adminer:
    image: adminer:4.8.1
    container_name: ultimate-crud-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - ultimate-crud-network
    depends_on:
      - mysql
      - postgres

  # phpMyAdmin - MySQL Management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: ultimate-crud-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: bloguser
      PMA_PASSWORD: blogpassword
    ports:
      - "8081:80"
    networks:
      - ultimate-crud-network
    depends_on:
      - mysql

  # pgAdmin - PostgreSQL Management
  pgadmin:
    image: dpage/pgadmin4:7
    container_name: ultimate-crud-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8082:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ultimate-crud-network
    depends_on:
      - postgres

volumes:
  mysql_data:
    driver: local
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  ultimate-crud-network:
    driver: bridge
